INSERT INTO extension(extension, enabled) VALUES ('txt', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('doc', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('xls', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('xlsx', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('csv', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('pdf', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('docx', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('ppt', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('jpg', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('jpeg', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('png', TRUE)
INSERT INTO extension(extension, enabled) VALUES ('gif', TRUE)

INSERT INTO app_user(account_non_expired, account_non_locked,credentials_non_expired, enabled, password, user_role, email) VALUES(TRUE,TRUE,TRUE,TRUE,'$2a$10$mW/t4UuKsq2InKxsMM3uoO6ACbw96vSH9oPZesinLhncQqVP5qRUi','STANDARD_USER','standard@gmail.com')
INSERT INTO app_user(account_non_expired,account_non_locked,credentials_non_expired, enabled, password, user_role, email) VALUES(TRUE,TRUE,TRUE,TRUE,'$2a$10$mW/t4UuKsq2InKxsMM3uoO6ACbw96vSH9oPZesinLhncQqVP5qRUi','ADMINISTRATOR','admin@gmail.com')